#!/bin/bash

######################################
##                                  ##
##           Report System          ##
##           React Client           ##
##                                  ##
######################################

# Start react client hosted natively in node.js
# Uses development credentials from ~/vocsn-web/.env
# Monitors source files and automatically restarts on changes

# Start serving React client in node
echo "Starting MA React Client - Development"
cd ~/marwa/client
yarn
yarn start
