#!/bin/bash

######################################
##                                  ##
##         Report System            ##
##         Report Generator         ##
##                                  ##
######################################

# Start python daemon to manage worker scripts for:
#   - Generate reports
#   - Assemble report batches in zip files
#   - Perform regular cleanup
# Uses production credentials from ~/vocsn-web/.env
# Starts and enables the marwa-reports system service to
#   restart the daemon on crash and reboot

# Require root privileges
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Root permissions required."
    exit
fi

# Update configuration
sudo python3 /home/marwa/update_config.py "/home/marwa/.env.conf"

# Stop existing service if its running
if systemctl is-active --quiet marwa-reports
then
    echo "Stopping marwa-reports service"
    sudo systemctl stop marwa-reports
fi

# Start marwa-reports service
echo "Starting Report Generator - Production"
echo "Enabling marwa-reports service"
sudo systemctl enable marwa-reports
echo "Starting marwa-reports service"
sudo systemctl start marwa-reports
