#!/bin/bash

######################################
##                                  ##
##  VOCSN Multi-View Report System  ##
##         Report Generator         ##
##                                  ##
######################################

# Stops python daemon managing report generator
# Stops mvr-reports system service

# Require root privileges
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Root permissions required."
    exit
fi

# Stop mvr-reports service
echo "Stopping Multi-View Report Generator - Production"
echo "Disabling mvr-reports service on startup"
sudo systemctl disable mvr-reports
echo "Stopping mvr-reports service"
sudo systemctl stop mvr-reports

