#!/bin/bash

######################################
##                                  ##
##         Report System            ##
##         Report Generator         ##
##                                  ##
######################################

# Stops python daemon managing report generator
# Stops marwa-reports system service

# Require root privileges
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Root permissions required."
    exit
fi

# Stop marwa-reports service
echo "Stopping Multi-View Report Generator - Production"
echo "Disabling marwa-reports service on startup"
sudo systemctl disable marwa-reports
echo "Stopping marwa-reports service"
sudo systemctl stop marwa-reports

