#!/bin/bash

######################################
##                                  ##
##  VOCSN Multi-View Report System  ##
##          GraphQL Server          ##
##                                  ##
######################################

# Stop GraphQL server
# Stop and disable mvr-server system service

# Require root privileges
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Root permissions required."
    exit
fi

# Stop and disable mvr-reports system service
echo "Stopping Multi-View GraphQL Server - Production"
echo "Stopping mvr-server service on startup"
sudo systemctl stop mvr-server
echo "Disabling mvr-server service"
sudo systemctl disable mvr-server

