#!/bin/bash

######################################
##                                  ##
##  VOCSN Multi-View Report System  ##
##          GraphQL Server          ##
##                                  ##
######################################

# Start GraphQL server as compiled code
# Uses production credentials from ~/vocsn-web/.env

# Require root privileges
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Root permissions required."
    exit
fi

# Preserve path
path="$(dirname "${BASH_SOURCE[0]}")"
cd "$path"

# Update configuration
sudo python3 ../update_config.py ../.env.conf

# Stop existing service if its running
if systemctl is-active --quiet mvr-server
then
    echo "Stopping mvr-server service"
    sudo systemctl stop mvr-server
fi

# Rebuild server
./server-startup.sh force

# Start mvr-server service
echo "Enabling mvr-server service"
sudo systemctl enable mvr-server
echo "Starting mvr-server service"
sudo systemctl start mvr-server
